Add M68K target to clang trunk (#55)
Currently choosing "M68k clang (trunk)" results in:
```
error: unable to create target: 'No available targets are compatible with triple "m68k"'
```

M68k is an experimental target so it needs to be added to
LLVM_EXPERIMENTAL_TARGETS_TO_BUILD to be included in clang.

I also checked locally that `-target m68k` is correct, so once clang
has the target it should start working.

```
$ ./bin/clang -target m68k /tmp/test.c -S -o -
        .text
        .file   "test.c"
        .globl  square                          ; -- Begin function square
<...>
```

Refs: https://github.com/compiler-explorer/compiler-explorer/issues/4904